Feature finegrained speech control
openbase/bco.psc pull request #10
Opened 2020-04-01 06:51 UTC by tugdil

2020-06-22 09:47 UTC, DivineThreepwood commented
Hey Matthias(@tugdil), 
sorry for my late response. In order to improve the openbase pull request procedure, I created some pull request and java guidelines at https://openbase.org/guidelines/#code-guidelines

Could you revise your code regarding this guidelines again? Once you are finished just leave a comment and I will take over the revise. Feel free to ask any questions here or directly via discord: https://discord.gg/9Zhd2j2

2020-07-01 09:20 UTC, tugdil commented
reviewed the code and removed some artefacts regarding the old version of the speech recognizer (grammar tree).
for the code guidelines (https://openbase.org/guidelines/#code-guidelines) it looks good as far as i've seen.
Only in KeywordConverter.java the function getActionParameter can return null but that was already the case before my changes.

2020-07-01 09:43 UTC, DivineThreepwood commented
Thanks, I will finish my revise end of the week.

2020-07-12 22:02 UTC, DivineThreepwood requested changes
Thanks for the PR :) Code looks pretty good.  There are just some minor changes requested.  
Just be aware, there are still two commits left on your forked master branch that are not part of the PR (e25b6da, 03d3ecf).

Cheers!
Marian

2020-07-13 06:42 UTC, tugdil commented on .idea/misc.xml
> -</project>
I don't understand this one. The </project> tag is still there in .idea/misc.xml

2020-07-13 13:26 UTC, DivineThreepwood commented on .idea/misc.xml
> -</project>
I do not complain about any missing tag but about the white space modification unrelated to the pr. 
-> checkout 1.1.4 in: https://openbase.org/guidelines/#_1-contribution-guidelines

2020-07-13 13:39 UTC, DivineThreepwood commented on .idea/misc.xml
> -</project>
you just need to perform `git checkout experimental .idea/misc.xm` in your pr branch.

2020-07-13 13:56 UTC, DivineThreepwood requested changes

2020-07-13 13:56 UTC, DivineThreepwood commented on speech/src/main/java/org/openbase/bco/psc/speech/SpeechController.java
> +    /***
It's still there right?

2020-07-14 11:30 UTC, DivineThreepwood commented
Nice, just replace the `e.printStackTrace();`with the `ExceptionPrinter` usage and we are ready to go :)

2020-07-19 17:06 UTC, DivineThreepwood approved these changes

2020-07-19 17:11 UTC, DivineThreepwood commented
@tugdil You just forgot to add some Imports. Next time please check if your code compiles before committing your changes :p However, I fixed all syntax errors and cleaned up some further code sections. PR is therefore ready to be merged.

2020-07-19 17:11 UTC, merged